### PR TITLE
Add expanded gist syntax

### PR DESCRIPTION
**Pull request by sukima**
This add the ability for a gist in the YAML fron matter to designate a specific file in a gist not just the entire thing.

```

---
gist: expalmer/4bc6203dc2a3f7134e78 sukima/510438:load_config.rb

---
```

By appending a `:filename` to the list it will be parsed to the following url:

```
https://gist.github.com/sukima/510438.json?file=load_config.rb
```

You reference the gist in the document the same way:

```
gist:sukima/510438:load_config.rb
```

### CODE REVIEW

**Comment by expalmer** [comment]
Hi Sukima, great job man, thanks for your improvements. I have a problem when a file is called with "-", but a will fix it.
Thanks.

**Comment by sukima** [comment]
What's the error you get in the console? I'm not seeing it.

**Comment by expalmer** [comment]
Ah...this error is my, a little error, because when the name file is "the-file-name.js", then the function app.helpers.toArray slit it in 3 files. Then I will change the `.replace(/([\s-,])/g,'|')` to `.replace(/([\s,])/g,'|')` removing the "-".
Thanks for you help and I hope that you have more improvements ;)

**Comment by sukima** [comment]
Glad to help. And yes: #2

**Pull request merged**
